#!/usr/bin/env python3
"""
Generate or update knowledge base description from tree index and wiki overview.

Usage:
    python tools/describe.py --kb <name>
    python tools/describe.py --kb <name> --set "custom description"  # set manually

The description is generated by analyzing:
- tree/index.json: topic structure and keywords
- wiki/overview.md: current synthesis content
"""

import sys
import json
import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
META_FILE = REPO_ROOT / "meta.json"

sys.path.insert(0, str(Path(__file__).parent))
from utils import call_claude_text, read_json


def read_file(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write_file(path: Path, content: str):
    path.write_text(content, encoding="utf-8")


def resolve_kb(kb_name: str | None) -> tuple[Path, Path, Path]:
    meta = read_json(META_FILE, {})

    if kb_name is None:
        kb_name = meta.get("default")

    if not kb_name:
        print("Error: no knowledge base specified and no default set.")
        print("Use --kb <name>")
        sys.exit(1)

    kb_path = REPO_ROOT / "knowledge_bases" / kb_name
    if not kb_path.exists():
        print(f"Error: knowledge base not found: {kb_name}")
        sys.exit(1)

    return kb_path, kb_path / "wiki", kb_path / "tree" / "index.json"


def generate_description(kb_path: Path, wiki_dir: Path, tree_file: Path) -> str:
    """Generate a description by analyzing tree structure and wiki overview."""

    # Collect tree topics and keywords
    topics = []
    leaf_count = 0

    def traverse_tree(node: dict, depth: int = 0):
        nonlocal leaf_count
        if node.get("type") == "topic":
            name = node.get("name", "")
            desc = node.get("description", "")
            keywords = node.get("keywords", [])
            topics.append(f"- {name}: {desc} (keywords: {', '.join(keywords[:5])})")
            for child in node.get("children", []):
                traverse_tree(child, depth + 1)
        elif node.get("type") == "leaf":
            leaf_count += 1

    if tree_file.exists():
        try:
            tree_data = json.loads(tree_file.read_text())
            for child in tree_data.get("children", []):
                traverse_tree(child)
        except json.JSONDecodeError:
            pass

    overview = read_file(wiki_dir / "overview.md")
    overview_preview = overview[:800] if overview else "(empty)"

    prompt = f"""Analyze this knowledge base and generate a concise description (2-3 sentences).

Tree structure (topics and their keywords):
{chr(10).join(topics) if topics else "(no topics yet)"}

Total source documents: {leaf_count}

Wiki overview (first 800 chars):
{overview_preview}

Based on the topics, keywords, and overview content, write a brief description that:
1. Explains what this knowledge base covers
2. Mentions the main topics/themes
3. Is suitable as a knowledge base summary

Write in the same language as the content (Chinese or English).
Keep it to 2-3 sentences. Start directly with the description, no prefix."""

    print("  analyzing tree structure and wiki content...")
    description = call_claude_text(prompt).strip()

    # Remove quotes if Claude added them
    if description.startswith('"') and description.endswith('"'):
        description = description[1:-1]
    if description.startswith("'") and description.endswith("'"):
        description = description[1:-1]

    return description


def update_meta_description(kb_name: str, description: str):
    """Update the description in meta.json for this knowledge base."""
    meta = read_json(META_FILE, {})

    alias_map = meta.get("alias_map", {})

    # Support both old format (string) and new format (object)
    if isinstance(alias_map.get(kb_name), str):
        alias_map[kb_name] = {"alias": alias_map[kb_name], "description": description}
    else:
        entry = alias_map.get(kb_name, {})
        if isinstance(entry, dict):
            entry["description"] = description
        else:
            entry = {"alias": "", "description": description}
        alias_map[kb_name] = entry

    meta["alias_map"] = alias_map
    write_file(META_FILE, json.dumps(meta, indent=2, ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser(description="Generate knowledge base description")
    parser.add_argument("--kb", type=str, default=None, help="Knowledge base name")
    parser.add_argument("--set", type=str, default=None,
                        help="Set description manually instead of generating")
    args = parser.parse_args()

    kb_path, wiki_dir, tree_file = resolve_kb(args.kb)
    kb_name = kb_path.name

    if args.set:
        description = args.set
        print(f"Setting description: {description}")
    else:
        description = generate_description(kb_path, wiki_dir, tree_file)
        print(f"Generated description: {description}")

    update_meta_description(kb_name, description)
    print(f"  updated: meta.json")


if __name__ == "__main__":
    main()
